name: redpanda-quickstart
networks:
  redpanda_network:
    driver: bridge
volumes:
  redpanda-0: null
  grafanadata:
  prometheusdata:
  lokidata:
  tempodata:

services:
  redpanda-0:
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      # Address the broker advertises to clients that connect to the Kafka API.
      # Use the internal addresses to connect to the Redpanda brokers'
      # from inside the same Docker network.
      # Use the external addresses to connect to the Redpanda brokers'
      # from outside the Docker network.
      - --advertise-kafka-addr internal://redpanda-0:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      # Address the broker advertises to clients that connect to the HTTP Proxy.
      - --advertise-pandaproxy-addr internal://redpanda-0:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      # Redpanda brokers use the RPC API to communicate with eachother internally.
      - --rpc-addr redpanda-0:33145
      - --advertise-rpc-addr redpanda-0:33145
      # Tells Seastar (the framework Redpanda uses under the hood) to use 1 core on the system.
      - --smp 1
      # The amount of memory to make available to Redpanda.
      - --memory 1G
      # Mode dev-container uses well-known configuration properties for development in containers.
      - --mode dev-container
      # enable logs for debugging.
      - --default-log-level=debug
    image: docker.redpanda.com/redpandadata/redpanda:v23.2.12
    container_name: redpanda-0
    volumes:
      - redpanda-0:/var/lib/redpanda/data
    networks:
      - redpanda_network
    expose:
      - 9644
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    depends_on:
      - prometheus
  console:
    container_name: redpanda-console
    image: docker.redpanda.com/redpandadata/console:v2.3.1
    networks:
      - redpanda_network
    entrypoint: /bin/sh
    command: -c 'echo "$$CONSOLE_CONFIG_FILE" > /tmp/config.yml; /app/console'
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda-0:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda-0:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda-0:9644"]
    ports:
      - 8080:8080
    depends_on:
      - redpanda-0

  # was partially following this guide here: https://evoila.com/blog/building-open-source-observability-stack-opentelemetry/
  # if having troubles we can take a look at this: https://dev.to/akinfiyinfoluwa/using-redpanda-with-opentelemetry-and-grafana-for-real-time-event-monitoring-li6
  collector:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:latest
    networks:
      - redpanda_network
    volumes:
      - ./otel_config/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    restart: no
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    networks:
      - redpanda_network
    volumes:
      - ./otel_config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./otel_data/prometheusdata:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver
      - --web.enable-otlp-receiver
      - --enable-feature=exemplar-storage
      - --storage.tsdb.retention.time=15d
    restart: no
    ports:
      - '9090:9090'
    depends_on:
      - collector

  loki:
    container_name: loki
    restart: no
    image: grafana/loki:latest
    networks:
      - redpanda_network
    volumes:
      - ./otel_data/lokidata:/loki
    ports:
      - "3100:3100"
    depends_on:
      - collector

  tempo:
    container_name: tempo
    restart: no
    image: grafana/tempo:latest
    volumes:
      - ./otel_config/tempo.yml:/etc/tempo.yml
      - ./otel_data/tempodata:/var/tempo
    command:
      - -config.file=/etc/tempo.yml
    ports:
      - "3200:3200"  # tempo

  grafana:
    container_name: grafana
    image: grafana/grafana
    networks:
      - redpanda_network
    restart: no
    volumes:
      - ./otel_config/grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - ./otel_data/grafanadata:/var/lib/grafana
    ports:
      - "3000:3000"
