version: "3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=thatcher
      - POSTGRES_PASSWORD=test
    ports:
      - 5432:5432
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/create_tables.sql:z